db:
  image: mongo:3.4.9
  ports:
    - 27017:27017
  command: --smallfiles
dicoinerBot:
  image: luger/dicoinerBot:latest
  environment:
      DB_URL: db
      DB_PORT: 27017
      TELEGRAM_KEY: "${TELEGRAM_KEY}"
  depends_on:
    - "db"
  command: ["./wait-for-it.sh", "db:27017"]